export const UPDATE_DOCUMENT_CONTENT = 'UPDATE_DOCUMENT_CONTENT'

export const UPDATE_DOCUMENT_NAME = 'UPDATE_DOCUMENT_NAME'

export const RESET_DOCUMENT_CHANGES = 'RESET_DOCUMENT_CHANGES'

export const TOGGLE_DOCUMENT_RENAME = 'TOGGLE_DOCUMENT_RENAME'
